version: '3.8'

services:
  db:
    image: postgres:15-alpine
    volumes:
      - postgres_data:/var/lib/postgresql/data
    environment:
      - POSTGRES_DB=adminpanel
      - POSTGRES_USER=admin
      - POSTGRES_PASSWORD=admin123
    ports:
      - "5432:5432"

  web:
    build: .
    command: sh -c "sleep 5 && python manage.py migrate && python manage.py runserver 0.0.0.0:8000"
    volumes:
      - .:/app
    ports:
      - "8000:8000"
    environment:
      - DATABASE_URL=postgresql://admin:admin123@db:5432/adminpanel
      - DEBUG=True
      - SECRET_KEY=django-insecure-change-this-in-production
      - ALLOWED_HOSTS=localhost,127.0.0.1,10.0.2.2,0.0.0.0
    depends_on:
      - db
    restart: on-failure

volumes:
  postgres_data:
