# Generated by Django 4.2.28 on 2026-02-06 02:48

from django.conf import settings
from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    dependencies = [
        ('accounts', '0006_add_user_fields_and_bankaccount'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='user',
            name='aadhar_card',
        ),
        migrations.RemoveField(
            model_name='user',
            name='email_notifications',
        ),
        migrations.RemoveField(
            model_name='user',
            name='pan_card',
        ),
        migrations.RemoveField(
            model_name='user',
            name='push_notifications',
        ),
        migrations.RemoveField(
            model_name='user',
            name='work',
        ),
        migrations.RemoveField(
            model_name='user',
            name='work_address',
        ),
        migrations.AddField(
            model_name='user',
            name='aadhar_copy',
            field=models.FileField(blank=True, null=True, upload_to='kyc/aadhar/'),
        ),
        migrations.AddField(
            model_name='user',
            name='aadhar_number',
            field=models.CharField(blank=True, max_length=12, null=True, verbose_name='Aadhaar Number'),
        ),
        migrations.AddField(
            model_name='user',
            name='active_fd_accounts',
            field=models.IntegerField(default=0, editable=False),
        ),
        migrations.AddField(
            model_name='user',
            name='active_loan_accounts',
            field=models.IntegerField(default=0, editable=False),
        ),
        migrations.AddField(
            model_name='user',
            name='active_rd_accounts',
            field=models.IntegerField(default=0, editable=False),
        ),
        migrations.AddField(
            model_name='user',
            name='active_savings_accounts',
            field=models.IntegerField(default=0, editable=False),
        ),
        migrations.AddField(
            model_name='user',
            name='address_proof',
            field=models.FileField(blank=True, null=True, upload_to='kyc/address/'),
        ),
        migrations.AddField(
            model_name='user',
            name='alt_nominee_contact',
            field=models.CharField(blank=True, max_length=15, null=True),
        ),
        migrations.AddField(
            model_name='user',
            name='alt_nominee_dob',
            field=models.DateField(blank=True, null=True),
        ),
        migrations.AddField(
            model_name='user',
            name='alt_nominee_name',
            field=models.CharField(blank=True, max_length=200, null=True),
        ),
        migrations.AddField(
            model_name='user',
            name='alt_nominee_relationship',
            field=models.CharField(blank=True, max_length=100, null=True),
        ),
        migrations.AddField(
            model_name='user',
            name='aml_check_status',
            field=models.CharField(blank=True, max_length=50, null=True, verbose_name='AML Check Status'),
        ),
        migrations.AddField(
            model_name='user',
            name='annual_income_bracket',
            field=models.CharField(blank=True, max_length=100, null=True),
        ),
        migrations.AddField(
            model_name='user',
            name='board_approval_reference',
            field=models.CharField(blank=True, max_length=100, null=True),
        ),
        migrations.AddField(
            model_name='user',
            name='closure_reason',
            field=models.TextField(blank=True, null=True, verbose_name='Reason for Closure'),
        ),
        migrations.AddField(
            model_name='user',
            name='current_address_line1',
            field=models.CharField(blank=True, max_length=255, null=True),
        ),
        migrations.AddField(
            model_name='user',
            name='current_address_line2',
            field=models.CharField(blank=True, max_length=255, null=True),
        ),
        migrations.AddField(
            model_name='user',
            name='current_city',
            field=models.CharField(blank=True, max_length=100, null=True),
        ),
        migrations.AddField(
            model_name='user',
            name='current_country',
            field=models.CharField(default='India', max_length=100),
        ),
        migrations.AddField(
            model_name='user',
            name='current_district',
            field=models.CharField(blank=True, max_length=100, null=True),
        ),
        migrations.AddField(
            model_name='user',
            name='current_pincode',
            field=models.CharField(blank=True, max_length=10, null=True),
        ),
        migrations.AddField(
            model_name='user',
            name='current_state',
            field=models.CharField(blank=True, max_length=100, null=True),
        ),
        migrations.AddField(
            model_name='user',
            name='date_of_birth',
            field=models.DateField(blank=True, null=True, verbose_name='Date of Birth'),
        ),
        migrations.AddField(
            model_name='user',
            name='date_of_joining',
            field=models.DateField(blank=True, null=True, verbose_name='Date of Joining'),
        ),
        migrations.AddField(
            model_name='user',
            name='dividend_payable_balance',
            field=models.DecimalField(decimal_places=2, default=0.0, max_digits=12),
        ),
        migrations.AddField(
            model_name='user',
            name='dnd_enabled',
            field=models.BooleanField(default=False, verbose_name='Do Not Disturb'),
        ),
        migrations.AddField(
            model_name='user',
            name='driving_license',
            field=models.CharField(blank=True, max_length=20, null=True),
        ),
        migrations.AddField(
            model_name='user',
            name='education_qualification',
            field=models.CharField(blank=True, max_length=200, null=True),
        ),
        migrations.AddField(
            model_name='user',
            name='eligible_for_accounts',
            field=models.BooleanField(default=True),
        ),
        migrations.AddField(
            model_name='user',
            name='eligible_for_dividend',
            field=models.BooleanField(default=True),
        ),
        migrations.AddField(
            model_name='user',
            name='eligible_for_loans',
            field=models.BooleanField(default=True),
        ),
        migrations.AddField(
            model_name='user',
            name='eligible_for_voting',
            field=models.BooleanField(default=True),
        ),
        migrations.AddField(
            model_name='user',
            name='exit_date',
            field=models.DateField(blank=True, null=True, verbose_name='Exit/Closure Date'),
        ),
        migrations.AddField(
            model_name='user',
            name='face_value_per_share',
            field=models.DecimalField(decimal_places=2, default=0.0, max_digits=10),
        ),
        migrations.AddField(
            model_name='user',
            name='full_name',
            field=models.CharField(blank=True, default='', max_length=200, verbose_name='Full Name (As per KYC)'),
        ),
        migrations.AddField(
            model_name='user',
            name='gender',
            field=models.CharField(blank=True, choices=[('male', 'Male'), ('female', 'Female'), ('other', 'Other')], max_length=10, null=True),
        ),
        migrations.AddField(
            model_name='user',
            name='internal_remarks',
            field=models.TextField(blank=True, null=True, verbose_name='Internal Notes'),
        ),
        migrations.AddField(
            model_name='user',
            name='introducer_approval_date',
            field=models.DateField(blank=True, null=True),
        ),
        migrations.AddField(
            model_name='user',
            name='introducer_member',
            field=models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.SET_NULL, related_name='introduced_members', to=settings.AUTH_USER_MODEL),
        ),
        migrations.AddField(
            model_name='user',
            name='kyc_status',
            field=models.CharField(choices=[('pending', 'Pending'), ('verified', 'Verified'), ('rejected', 'Rejected'), ('expired', 'Expired')], default='pending', max_length=20),
        ),
        migrations.AddField(
            model_name='user',
            name='kyc_verified_by',
            field=models.CharField(blank=True, max_length=200, null=True),
        ),
        migrations.AddField(
            model_name='user',
            name='kyc_verified_date',
            field=models.DateField(blank=True, null=True),
        ),
        migrations.AddField(
            model_name='user',
            name='last_compliance_review_date',
            field=models.DateField(blank=True, null=True),
        ),
        migrations.AddField(
            model_name='user',
            name='last_dividend_paid_date',
            field=models.DateField(blank=True, null=True),
        ),
        migrations.AddField(
            model_name='user',
            name='marital_status',
            field=models.CharField(blank=True, choices=[('single', 'Single'), ('married', 'Married'), ('divorced', 'Divorced'), ('widowed', 'Widowed')], max_length=20, null=True),
        ),
        migrations.AddField(
            model_name='user',
            name='member_id',
            field=models.CharField(blank=True, max_length=50, null=True, unique=True, verbose_name='Member ID'),
        ),
        migrations.AddField(
            model_name='user',
            name='member_type',
            field=models.CharField(choices=[('regular', 'Regular'), ('nominal', 'Nominal'), ('associate', 'Associate'), ('staff', 'Staff')], default='regular', max_length=20),
        ),
        migrations.AddField(
            model_name='user',
            name='mobile_alternate',
            field=models.CharField(blank=True, max_length=15, null=True, verbose_name='Alternate Mobile'),
        ),
        migrations.AddField(
            model_name='user',
            name='mobile_primary',
            field=models.CharField(blank=True, max_length=15, null=True, verbose_name='Primary Mobile'),
        ),
        migrations.AddField(
            model_name='user',
            name='nominee_address',
            field=models.TextField(blank=True, null=True),
        ),
        migrations.AddField(
            model_name='user',
            name='nominee_contact',
            field=models.CharField(blank=True, max_length=15, null=True),
        ),
        migrations.AddField(
            model_name='user',
            name='nominee_dob',
            field=models.DateField(blank=True, null=True, verbose_name='Nominee Date of Birth'),
        ),
        migrations.AddField(
            model_name='user',
            name='nominee_id_number',
            field=models.CharField(blank=True, max_length=50, null=True),
        ),
        migrations.AddField(
            model_name='user',
            name='nominee_id_type',
            field=models.CharField(blank=True, max_length=50, null=True),
        ),
        migrations.AddField(
            model_name='user',
            name='nominee_name',
            field=models.CharField(blank=True, max_length=200, null=True),
        ),
        migrations.AddField(
            model_name='user',
            name='nominee_relationship',
            field=models.CharField(blank=True, max_length=100, null=True),
        ),
        migrations.AddField(
            model_name='user',
            name='number_of_shares',
            field=models.IntegerField(default=0),
        ),
        migrations.AddField(
            model_name='user',
            name='occupation',
            field=models.CharField(blank=True, max_length=200, null=True),
        ),
        migrations.AddField(
            model_name='user',
            name='pan_copy',
            field=models.FileField(blank=True, null=True, upload_to='kyc/pan/'),
        ),
        migrations.AddField(
            model_name='user',
            name='pan_number',
            field=models.CharField(blank=True, max_length=10, null=True, verbose_name='PAN Number'),
        ),
        migrations.AddField(
            model_name='user',
            name='passport_number',
            field=models.CharField(blank=True, max_length=20, null=True),
        ),
        migrations.AddField(
            model_name='user',
            name='permanent_address_line1',
            field=models.CharField(blank=True, max_length=255, null=True),
        ),
        migrations.AddField(
            model_name='user',
            name='permanent_address_line2',
            field=models.CharField(blank=True, max_length=255, null=True),
        ),
        migrations.AddField(
            model_name='user',
            name='permanent_city',
            field=models.CharField(blank=True, max_length=100, null=True),
        ),
        migrations.AddField(
            model_name='user',
            name='permanent_country',
            field=models.CharField(default='India', max_length=100),
        ),
        migrations.AddField(
            model_name='user',
            name='permanent_district',
            field=models.CharField(blank=True, max_length=100, null=True),
        ),
        migrations.AddField(
            model_name='user',
            name='permanent_pincode',
            field=models.CharField(blank=True, max_length=10, null=True),
        ),
        migrations.AddField(
            model_name='user',
            name='permanent_same_as_current',
            field=models.BooleanField(default=True),
        ),
        migrations.AddField(
            model_name='user',
            name='permanent_state',
            field=models.CharField(blank=True, max_length=100, null=True),
        ),
        migrations.AddField(
            model_name='user',
            name='photograph',
            field=models.ImageField(blank=True, null=True, upload_to='kyc/photos/'),
        ),
        migrations.AddField(
            model_name='user',
            name='portal_access_enabled',
            field=models.BooleanField(default=True),
        ),
        migrations.AddField(
            model_name='user',
            name='preferred_comm_mode',
            field=models.CharField(choices=[('sms', 'SMS'), ('email', 'Email'), ('whatsapp', 'WhatsApp'), ('letter', 'Letter')], default='email', max_length=20),
        ),
        migrations.AddField(
            model_name='user',
            name='risk_category',
            field=models.CharField(choices=[('low', 'Low'), ('medium', 'Medium'), ('high', 'High')], default='low', max_length=20),
        ),
        migrations.AddField(
            model_name='user',
            name='share_capital_amount',
            field=models.DecimalField(decimal_places=2, default=0.0, max_digits=12),
        ),
        migrations.AddField(
            model_name='user',
            name='share_certificate_number',
            field=models.CharField(blank=True, max_length=50, null=True),
        ),
        migrations.AddField(
            model_name='user',
            name='share_issue_date',
            field=models.DateField(blank=True, null=True),
        ),
        migrations.AddField(
            model_name='user',
            name='signature_specimen',
            field=models.ImageField(blank=True, null=True, upload_to='kyc/signatures/'),
        ),
        migrations.AddField(
            model_name='user',
            name='status',
            field=models.CharField(choices=[('active', 'Active'), ('inactive', 'Inactive'), ('closed', 'Closed'), ('deceased', 'Deceased'), ('blacklisted', 'Blacklisted')], default='active', max_length=20),
        ),
        migrations.AddField(
            model_name='user',
            name='total_accounts_count',
            field=models.IntegerField(default=0, editable=False),
        ),
        migrations.AddField(
            model_name='user',
            name='total_deposit_balance',
            field=models.DecimalField(decimal_places=2, default=0.0, editable=False, max_digits=15),
        ),
        migrations.AddField(
            model_name='user',
            name='total_loan_outstanding',
            field=models.DecimalField(decimal_places=2, default=0.0, editable=False, max_digits=15),
        ),
        migrations.AddField(
            model_name='user',
            name='voter_id',
            field=models.CharField(blank=True, max_length=20, null=True, verbose_name='Voter ID'),
        ),
        migrations.AlterField(
            model_name='user',
            name='role',
            field=models.CharField(default='member', max_length=20),
        ),
    ]
