# Generated by Django 4.2.28 on 2026-02-06 03:10

import django.core.validators
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('accounts', '0007_remove_user_aadhar_card_and_more'),
    ]

    operations = [
        migrations.AlterField(
            model_name='bankaccount',
            name='ifsc_code',
            field=models.CharField(blank=True, max_length=11, null=True, validators=[django.core.validators.RegexValidator(message='IFSC must be 11 characters: 4 letters + 0 + 6 alphanumeric', regex='^[A-Z]{4}0[A-Z0-9]{6}$')], verbose_name='IFSC Code'),
        ),
        migrations.AlterField(
            model_name='user',
            name='aadhar_number',
            field=models.CharField(blank=True, max_length=12, null=True, validators=[django.core.validators.RegexValidator(message='Aadhaar must be 12 digits and cannot start with 0 or 1', regex='^[2-9][0-9]{11}$')], verbose_name='Aadhaar Number'),
        ),
        migrations.AlterField(
            model_name='user',
            name='current_pincode',
            field=models.CharField(blank=True, max_length=10, null=True, validators=[django.core.validators.RegexValidator(message='Pincode must be 6 digits and cannot start with 0', regex='^[1-9][0-9]{5}$')]),
        ),
        migrations.AlterField(
            model_name='user',
            name='mobile_alternate',
            field=models.CharField(blank=True, max_length=15, null=True, validators=[django.core.validators.RegexValidator(message='Phone must be 10 digits starting with 6, 7, 8, or 9', regex='^[6-9][0-9]{9}$')], verbose_name='Alternate Mobile'),
        ),
        migrations.AlterField(
            model_name='user',
            name='mobile_primary',
            field=models.CharField(blank=True, max_length=15, null=True, validators=[django.core.validators.RegexValidator(message='Phone must be 10 digits starting with 6, 7, 8, or 9', regex='^[6-9][0-9]{9}$')], verbose_name='Primary Mobile'),
        ),
        migrations.AlterField(
            model_name='user',
            name='pan_number',
            field=models.CharField(blank=True, max_length=10, null=True, validators=[django.core.validators.RegexValidator(message='PAN must be in format: ABCDE1234F (5 letters, 4 digits, 1 letter)', regex='^[A-Z]{5}[0-9]{4}[A-Z]$')], verbose_name='PAN Number'),
        ),
        migrations.AlterField(
            model_name='user',
            name='permanent_pincode',
            field=models.CharField(blank=True, max_length=10, null=True, validators=[django.core.validators.RegexValidator(message='Pincode must be 6 digits and cannot start with 0', regex='^[1-9][0-9]{5}$')]),
        ),
    ]
