# Generated by Django 4.2.28 on 2026-02-07 05:25

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('accounts', '0009_alter_user_email'),
    ]

    operations = [
        migrations.AlterField(
            model_name='user',
            name='member_id',
            field=models.CharField(blank=True, db_index=True, max_length=50, null=True, unique=True, verbose_name='Member ID'),
        ),
        migrations.AlterField(
            model_name='user',
            name='member_type',
            field=models.CharField(choices=[('regular', 'Regular'), ('nominal', 'Nominal'), ('associate', 'Associate'), ('staff', 'Staff')], db_index=True, default='regular', max_length=20),
        ),
        migrations.AlterField(
            model_name='user',
            name='role',
            field=models.CharField(db_index=True, default='member', max_length=20),
        ),
        migrations.AlterField(
            model_name='user',
            name='status',
            field=models.CharField(choices=[('active', 'Active'), ('inactive', 'Inactive'), ('closed', 'Closed'), ('deceased', 'Deceased'), ('blacklisted', 'Blacklisted')], db_index=True, default='active', max_length=20),
        ),
    ]
