# Generated by Django 4.2.28 on 2026-02-08 13:58

from django.conf import settings
from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    dependencies = [
        ('accounts', '0010_alter_user_member_id_alter_user_member_type_and_more'),
    ]

    operations = [
        migrations.CreateModel(
            name='MemberAccount',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('account_number', models.CharField(db_index=True, max_length=20, unique=True)),
                ('account_type', models.CharField(choices=[('savings', 'Savings Account'), ('fd', 'Fixed Deposit'), ('rd', 'Recurring Deposit'), ('current', 'Current Account'), ('cd', 'Certificate of Deposit')], db_index=True, max_length=20)),
                ('status', models.CharField(choices=[('active', 'Active'), ('closed', 'Closed'), ('frozen', 'Frozen'), ('matured', 'Matured'), ('dormant', 'Dormant')], db_index=True, default='active', max_length=20)),
                ('balance', models.DecimalField(decimal_places=2, default=0.0, max_digits=15)),
                ('interest_rate', models.DecimalField(decimal_places=2, default=0.0, max_digits=5, verbose_name='Interest Rate (%)')),
                ('principal_amount', models.DecimalField(decimal_places=2, default=0.0, max_digits=15, verbose_name='Principal Amount')),
                ('accrued_interest', models.DecimalField(decimal_places=2, default=0.0, max_digits=15, verbose_name='Accrued Interest')),
                ('rd_monthly_amount', models.DecimalField(blank=True, decimal_places=2, max_digits=12, null=True, verbose_name='RD Monthly Installment')),
                ('rd_installments_paid', models.IntegerField(default=0, verbose_name='Installments Paid')),
                ('rd_total_installments', models.IntegerField(blank=True, null=True, verbose_name='Total Installments')),
                ('opening_date', models.DateField(verbose_name='Account Opening Date')),
                ('maturity_date', models.DateField(blank=True, null=True, verbose_name='Maturity Date')),
                ('closure_date', models.DateField(blank=True, null=True, verbose_name='Closure Date')),
                ('last_transaction_date', models.DateField(blank=True, null=True)),
                ('last_interest_calc_date', models.DateField(blank=True, null=True)),
                ('tenure_months', models.IntegerField(blank=True, null=True, verbose_name='Tenure (Months)')),
                ('nominee_name', models.CharField(blank=True, max_length=200, null=True)),
                ('nominee_relationship', models.CharField(blank=True, max_length=100, null=True)),
                ('remarks', models.TextField(blank=True, null=True)),
                ('created_at', models.DateTimeField(auto_now_add=True)),
                ('updated_at', models.DateTimeField(auto_now=True)),
                ('user', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='member_accounts', to=settings.AUTH_USER_MODEL)),
            ],
            options={
                'verbose_name': 'Member Account',
                'verbose_name_plural': 'Member Accounts',
                'ordering': ['-created_at'],
            },
        ),
    ]
