# Generated by Django 4.2.28 on 2026-02-10 20:30

from django.conf import settings
from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    dependencies = [
        ('accounts', '0012_receipt'),
    ]

    operations = [
        migrations.CreateModel(
            name='Loan',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('loan_number', models.CharField(db_index=True, max_length=20, unique=True)),
                ('loan_type', models.CharField(choices=[('personal', 'Personal Loan'), ('home', 'Home Loan'), ('vehicle', 'Vehicle Loan'), ('gold', 'Gold Loan'), ('education', 'Education Loan'), ('business', 'Business Loan'), ('emergency', 'Emergency Loan'), ('agriculture', 'Agriculture Loan')], db_index=True, max_length=20)),
                ('status', models.CharField(choices=[('pending', 'Pending Approval'), ('approved', 'Approved'), ('active', 'Active'), ('closed', 'Closed'), ('defaulted', 'Defaulted'), ('written_off', 'Written Off'), ('rejected', 'Rejected')], db_index=True, default='pending', max_length=20)),
                ('principal_amount', models.DecimalField(decimal_places=2, max_digits=15, verbose_name='Loan Amount')),
                ('interest_rate', models.DecimalField(decimal_places=2, max_digits=5, verbose_name='Interest Rate (% p.a.)')),
                ('interest_type', models.CharField(choices=[('flat', 'Flat Rate'), ('reducing', 'Reducing Balance')], default='reducing', max_length=20)),
                ('tenure_months', models.IntegerField(verbose_name='Tenure (Months)')),
                ('emi_amount', models.DecimalField(decimal_places=2, default=0.0, max_digits=12, verbose_name='EMI Amount')),
                ('total_payable', models.DecimalField(decimal_places=2, default=0.0, max_digits=15, verbose_name='Total Payable Amount')),
                ('total_paid', models.DecimalField(decimal_places=2, default=0.0, max_digits=15, verbose_name='Total Paid')),
                ('outstanding_balance', models.DecimalField(decimal_places=2, default=0.0, max_digits=15, verbose_name='Outstanding Balance')),
                ('overdue_amount', models.DecimalField(decimal_places=2, default=0.0, max_digits=15, verbose_name='Overdue Amount')),
                ('application_date', models.DateField(verbose_name='Application Date')),
                ('approval_date', models.DateField(blank=True, null=True, verbose_name='Approval Date')),
                ('disbursement_date', models.DateField(blank=True, null=True, verbose_name='Disbursement Date')),
                ('first_emi_date', models.DateField(blank=True, null=True, verbose_name='First EMI Date')),
                ('last_emi_date', models.DateField(blank=True, null=True, verbose_name='Last EMI Date')),
                ('closure_date', models.DateField(blank=True, null=True, verbose_name='Closure Date')),
                ('total_emis', models.IntegerField(default=0, verbose_name='Total EMIs')),
                ('emis_paid', models.IntegerField(default=0, verbose_name='EMIs Paid')),
                ('emis_overdue', models.IntegerField(default=0, verbose_name='EMIs Overdue')),
                ('guarantor_name', models.CharField(blank=True, max_length=200, null=True)),
                ('guarantor_member_id', models.CharField(blank=True, max_length=50, null=True)),
                ('guarantor_relationship', models.CharField(blank=True, max_length=100, null=True)),
                ('guarantor_contact', models.CharField(blank=True, max_length=15, null=True)),
                ('collateral_type', models.CharField(blank=True, max_length=200, null=True, verbose_name='Collateral Type')),
                ('collateral_value', models.DecimalField(blank=True, decimal_places=2, max_digits=15, null=True, verbose_name='Collateral Value')),
                ('collateral_description', models.TextField(blank=True, null=True, verbose_name='Collateral Description')),
                ('purpose', models.TextField(blank=True, null=True, verbose_name='Loan Purpose')),
                ('remarks', models.TextField(blank=True, null=True)),
                ('created_at', models.DateTimeField(auto_now_add=True)),
                ('updated_at', models.DateTimeField(auto_now=True)),
                ('approved_by', models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.SET_NULL, related_name='loans_approved', to=settings.AUTH_USER_MODEL, verbose_name='Approved By')),
                ('created_by', models.ForeignKey(null=True, on_delete=django.db.models.deletion.SET_NULL, related_name='loans_created', to=settings.AUTH_USER_MODEL, verbose_name='Created By')),
                ('disbursement_account', models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.SET_NULL, related_name='loans_disbursed', to='accounts.memberaccount', verbose_name='Disbursement Account')),
                ('user', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='loans', to=settings.AUTH_USER_MODEL)),
            ],
            options={
                'verbose_name': 'Loan',
                'verbose_name_plural': 'Loans',
                'ordering': ['-created_at'],
            },
        ),
        migrations.CreateModel(
            name='LoanRepayment',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('installment_number', models.IntegerField(verbose_name='Installment #')),
                ('due_date', models.DateField(verbose_name='Due Date')),
                ('paid_date', models.DateField(blank=True, null=True, verbose_name='Paid Date')),
                ('amount_due', models.DecimalField(decimal_places=2, max_digits=12, verbose_name='Amount Due')),
                ('amount_paid', models.DecimalField(decimal_places=2, default=0.0, max_digits=12, verbose_name='Amount Paid')),
                ('principal_component', models.DecimalField(decimal_places=2, default=0.0, max_digits=12, verbose_name='Principal Component')),
                ('interest_component', models.DecimalField(decimal_places=2, default=0.0, max_digits=12, verbose_name='Interest Component')),
                ('penalty', models.DecimalField(decimal_places=2, default=0.0, max_digits=10, verbose_name='Late Penalty')),
                ('balance_after', models.DecimalField(decimal_places=2, default=0.0, max_digits=15, verbose_name='Outstanding After Payment')),
                ('payment_status', models.CharField(choices=[('paid', 'Paid'), ('partial', 'Partial'), ('overdue', 'Overdue'), ('upcoming', 'Upcoming')], default='upcoming', max_length=20)),
                ('payment_mode', models.CharField(choices=[('cash', 'Cash'), ('cheque', 'Cheque'), ('online', 'Online Transfer'), ('neft', 'NEFT'), ('rtgs', 'RTGS'), ('upi', 'UPI')], default='cash', max_length=20)),
                ('reference_number', models.CharField(blank=True, max_length=100, null=True)),
                ('remarks', models.TextField(blank=True, null=True)),
                ('created_at', models.DateTimeField(auto_now_add=True)),
                ('loan', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='repayments', to='accounts.loan')),
                ('receipt', models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.SET_NULL, related_name='loan_repayments', to='accounts.receipt')),
            ],
            options={
                'verbose_name': 'Loan Repayment',
                'verbose_name_plural': 'Loan Repayments',
                'ordering': ['installment_number'],
                'unique_together': {('loan', 'installment_number')},
            },
        ),
    ]
