# Generated by Django 4.2.28 on 2026-02-11 16:55

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('accounts', '0013_loan_loanrepayment'),
    ]

    operations = [
        migrations.AlterField(
            model_name='memberaccount',
            name='account_type',
            field=models.CharField(choices=[('fd', 'Fixed Deposit'), ('cd', 'Certificate of Deposit'), ('rd', 'Recurring Deposit'), ('od', 'Overdraft'), ('share', 'Share Account'), ('sukanya', 'Sukanya Yojana'), ('suputra', 'Suputra Yojana')], db_index=True, max_length=20),
        ),
    ]
