# Generated by Django 4.2.28 on 2026-02-12 09:02

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('accounts', '0015_memberaccount_deleted_at_memberaccount_is_deleted_and_more'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='user',
            name='full_name',
        ),
    ]
