# Generated by Django 4.2.28 on 2026-02-12 09:20

from django.conf import settings
from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    dependencies = [
        ('accounts', '0016_remove_user_full_name'),
    ]

    operations = [
        migrations.CreateModel(
            name='AuditLog',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('action', models.CharField(choices=[('create', 'Create'), ('update', 'Update'), ('delete', 'Delete'), ('login', 'Login'), ('logout', 'Logout'), ('approve', 'Approve'), ('reject', 'Reject'), ('reset_password', 'Reset Password'), ('export', 'Export')], db_index=True, max_length=20)),
                ('entity_type', models.CharField(choices=[('member', 'Member'), ('account', 'Account'), ('receipt', 'Receipt'), ('loan', 'Loan'), ('system', 'System')], db_index=True, max_length=20)),
                ('entity_id', models.IntegerField(blank=True, null=True, verbose_name='Entity ID')),
                ('description', models.TextField(verbose_name='Action Description')),
                ('ip_address', models.GenericIPAddressField(blank=True, null=True)),
                ('created_at', models.DateTimeField(auto_now_add=True, db_index=True)),
                ('user', models.ForeignKey(null=True, on_delete=django.db.models.deletion.SET_NULL, related_name='audit_logs', to=settings.AUTH_USER_MODEL, verbose_name='Performed By')),
            ],
            options={
                'verbose_name': 'Audit Log',
                'verbose_name_plural': 'Audit Logs',
                'ordering': ['-created_at'],
            },
        ),
    ]
