# Generated by Django 4.2.27 on 2026-02-13 16:34

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('accounts', '0017_auditlog'),
    ]

    operations = [
        migrations.AlterField(
            model_name='loan',
            name='guarantor_contact',
            field=models.CharField(blank=True, max_length=30, null=True),
        ),
        migrations.AlterField(
            model_name='user',
            name='alt_nominee_contact',
            field=models.CharField(blank=True, max_length=30, null=True),
        ),
        migrations.AlterField(
            model_name='user',
            name='mobile_alternate',
            field=models.CharField(blank=True, max_length=30, null=True, verbose_name='Alternate Mobile'),
        ),
        migrations.AlterField(
            model_name='user',
            name='mobile_primary',
            field=models.CharField(blank=True, max_length=30, null=True, verbose_name='Primary Mobile'),
        ),
        migrations.AlterField(
            model_name='user',
            name='nominee_contact',
            field=models.CharField(blank=True, max_length=30, null=True),
        ),
    ]
