# Generated by Django 4.2.30 on 2026-04-08 01:56

from django.conf import settings
from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    dependencies = [
        ('accounts', '0019_fund_management'),
    ]

    operations = [
        migrations.AddField(
            model_name='loan',
            name='npa_date',
            field=models.DateField(blank=True, null=True, verbose_name='NPA Classification Date'),
        ),
        migrations.AddField(
            model_name='loan',
            name='processing_fee',
            field=models.DecimalField(decimal_places=2, default=0.0, max_digits=10, verbose_name='Processing Fee'),
        ),
        migrations.CreateModel(
            name='InterestPayout',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('amount', models.DecimalField(decimal_places=2, max_digits=12)),
                ('period_start', models.DateField()),
                ('period_end', models.DateField()),
                ('created_at', models.DateTimeField(auto_now_add=True)),
                ('account', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='interest_payouts', to='accounts.memberaccount')),
                ('created_by', models.ForeignKey(null=True, on_delete=django.db.models.deletion.SET_NULL, related_name='interest_payouts_created', to=settings.AUTH_USER_MODEL)),
            ],
            options={
                'verbose_name': 'Interest Payout',
                'verbose_name_plural': 'Interest Payouts',
                'ordering': ['-created_at'],
            },
        ),
    ]
