# Generated by Django 4.2.30 on 2026-04-09 21:28

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('accounts', '0023_loginotpchallenge_userdevice'),
    ]

    operations = [
        migrations.AddField(
            model_name='user',
            name='push_notifications_enabled',
            field=models.BooleanField(default=True, help_text="When off, the server will not send FCM messages to this member's devices.", verbose_name='Push Notifications'),
        ),
    ]
