# Generated by Django 4.2.30 on 2026-04-12 12:21

from django.conf import settings
import django.core.validators
from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    dependencies = [
        ('accounts', '0027_voucher_voucher_type'),
    ]

    operations = [
        migrations.CreateModel(
            name='FinancialPeriod',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('label', models.CharField(max_length=20, verbose_name='Period Label')),
                ('start_date', models.DateField(verbose_name='Period Start')),
                ('end_date', models.DateField(verbose_name='Period End')),
                ('status', models.CharField(choices=[('open', 'Open'), ('closed', 'Closed'), ('continuing', 'Continuing')], db_index=True, default='open', max_length=20)),
                ('is_active', models.BooleanField(default=True, verbose_name='Currently Active Period')),
                ('created_at', models.DateTimeField(auto_now_add=True)),
                ('updated_at', models.DateTimeField(auto_now=True)),
                ('created_by', models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.SET_NULL, related_name='financial_periods_created', to=settings.AUTH_USER_MODEL)),
            ],
            options={
                'verbose_name': 'Financial Period',
                'verbose_name_plural': 'Financial Periods',
                'ordering': ['-start_date'],
                'unique_together': {('start_date', 'end_date')},
            },
        ),
        migrations.CreateModel(
            name='Instrument',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('instrument_type', models.CharField(choices=[('cash', 'Cash'), ('cheque', 'Cheque'), ('dd', 'Demand Draft'), ('neft', 'NEFT'), ('rtgs', 'RTGS'), ('upi', 'UPI'), ('imps', 'IMPS')], db_index=True, max_length=20)),
                ('amount', models.DecimalField(decimal_places=2, max_digits=15)),
                ('cheque_number', models.CharField(blank=True, max_length=30, null=True)),
                ('drawer_name', models.CharField(blank=True, max_length=200, null=True)),
                ('drawer_bank', models.CharField(blank=True, max_length=200, null=True)),
                ('drawer_ifsc', models.CharField(blank=True, max_length=11, null=True, validators=[django.core.validators.RegexValidator(message='IFSC must be 11 characters: 4 letters + 0 + 6 alphanumeric', regex='^[A-Z]{4}0[A-Z0-9]{6}$')])),
                ('cheque_date', models.DateField(blank=True, null=True)),
                ('cheque_status', models.CharField(blank=True, choices=[('not_submitted', 'Not Submitted'), ('submitted', 'Submitted'), ('cleared', 'Cleared'), ('bounced', 'Bounced'), ('cancelled', 'Cancelled')], default='not_submitted', max_length=20, null=True)),
                ('reference_number', models.CharField(blank=True, max_length=100, null=True, verbose_name='UTR / Reference')),
                ('upi_vpa', models.CharField(blank=True, max_length=100, null=True, verbose_name='UPI VPA')),
                ('is_cleared', models.BooleanField(default=False)),
                ('clearing_date', models.DateField(blank=True, null=True)),
                ('bounce_reason', models.TextField(blank=True, null=True)),
                ('created_at', models.DateTimeField(auto_now_add=True)),
                ('updated_at', models.DateTimeField(auto_now=True)),
            ],
            options={
                'verbose_name': 'Instrument',
                'verbose_name_plural': 'Instruments',
                'ordering': ['-created_at'],
            },
        ),
        migrations.CreateModel(
            name='Transaction',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('transaction_number', models.CharField(db_index=True, max_length=20, unique=True)),
                ('transaction_type', models.CharField(choices=[('credit', 'Credit'), ('debit', 'Debit'), ('transfer', 'Transfer'), ('interest', 'Interest Payment'), ('dividend', 'Dividend'), ('share_capital', 'Share Capital')], db_index=True, max_length=20)),
                ('amount', models.DecimalField(decimal_places=2, max_digits=15)),
                ('description', models.TextField(blank=True, null=True)),
                ('payment_mode', models.CharField(choices=[('cash', 'Cash'), ('cheque', 'Cheque'), ('online', 'Online Transfer'), ('neft', 'NEFT'), ('rtgs', 'RTGS'), ('upi', 'UPI')], default='cash', max_length=20)),
                ('reference_number', models.CharField(blank=True, max_length=100, null=True, verbose_name='Reference / Cheque No.')),
                ('balance_after', models.DecimalField(decimal_places=2, default=0.0, max_digits=15, verbose_name='Balance After Transaction')),
                ('transaction_date', models.DateField(blank=True, null=True, verbose_name='Transaction Date')),
                ('remarks', models.TextField(blank=True, null=True)),
                ('created_at', models.DateTimeField(auto_now_add=True)),
                ('created_by', models.ForeignKey(null=True, on_delete=django.db.models.deletion.SET_NULL, related_name='transactions_created', to=settings.AUTH_USER_MODEL, verbose_name='Created By (Admin)')),
                ('instrument', models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.SET_NULL, related_name='transactions', to='accounts.instrument')),
                ('member_account', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='transactions', to='accounts.memberaccount')),
                ('user', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='transactions', to=settings.AUTH_USER_MODEL)),
            ],
            options={
                'verbose_name': 'Transaction',
                'verbose_name_plural': 'Transactions',
                'ordering': ['-created_at'],
            },
        ),
        migrations.RemoveField(
            model_name='loanrepayment',
            name='receipt',
        ),
        migrations.RemoveField(
            model_name='voucherentry',
            name='created_receipt',
        ),
        migrations.AddField(
            model_name='voucher',
            name='journal_narration',
            field=models.TextField(blank=True, null=True, verbose_name='Journal Narration'),
        ),
        migrations.AlterField(
            model_name='auditlog',
            name='entity_type',
            field=models.CharField(choices=[('member', 'Member'), ('account', 'Account'), ('transaction', 'Transaction'), ('voucher', 'Voucher'), ('loan', 'Loan'), ('fund', 'Fund'), ('system', 'System')], db_index=True, max_length=20),
        ),
        migrations.AlterField(
            model_name='voucher',
            name='voucher_type',
            field=models.CharField(choices=[('receipt', 'Receipt Voucher'), ('payment', 'Payment Voucher'), ('contra', 'Contra Voucher'), ('journal', 'Journal Voucher')], db_index=True, default='receipt', max_length=20),
        ),
        migrations.DeleteModel(
            name='Receipt',
        ),
        migrations.AddField(
            model_name='loanrepayment',
            name='transaction',
            field=models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.SET_NULL, related_name='loan_repayments', to='accounts.transaction'),
        ),
        migrations.AddField(
            model_name='voucherentry',
            name='created_transaction',
            field=models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.SET_NULL, related_name='voucher_entries', to='accounts.transaction'),
        ),
    ]
