# Generated by Django 4.2.30 on 2026-04-12 14:07
# Reordered: create sub-models → copy data from User → remove User columns (Phase 2).

from django.conf import settings
import django.core.validators
from django.db import migrations, models
import django.db.models.deletion


def phase2_copy_from_user(apps, schema_editor):
    """Copy KYC, addresses, nominees, and share capital from User into new tables."""
    from datetime import date
    from decimal import Decimal

    User = apps.get_model("accounts", "User")
    MemberKYC = apps.get_model("accounts", "MemberKYC")
    MemberAddress = apps.get_model("accounts", "MemberAddress")
    MemberNominee = apps.get_model("accounts", "MemberNominee")
    ShareCapital = apps.get_model("accounts", "ShareCapital")

    for user in User.objects.all():
        MemberKYC.objects.update_or_create(
            user_id=user.pk,
            defaults={
                "kyc_status": user.kyc_status or "pending",
                "kyc_verified_date": user.kyc_verified_date,
                "kyc_verified_by": user.kyc_verified_by,
                "aadhaar_number": user.aadhar_number,
                "pan_number": user.pan_number,
                "voter_id": user.voter_id,
                "passport_number": user.passport_number,
                "driving_licence": user.driving_license,
                "aadhaar_copy": user.aadhar_copy,
                "pan_copy": user.pan_copy,
                "address_proof": user.address_proof,
                "photograph": user.photograph,
                "signature_specimen": user.signature_specimen,
            },
        )

        MemberAddress.objects.update_or_create(
            user_id=user.pk,
            address_type="current",
            defaults={
                "address_line1": user.current_address_line1,
                "address_line2": user.current_address_line2,
                "city": user.current_city,
                "district": user.current_district,
                "state": user.current_state,
                "pincode": user.current_pincode,
                "country": user.current_country or "India",
                "same_as_current": False,
            },
        )

        if user.permanent_same_as_current:
            MemberAddress.objects.update_or_create(
                user_id=user.pk,
                address_type="permanent",
                defaults={
                    "address_line1": user.current_address_line1,
                    "address_line2": user.current_address_line2,
                    "city": user.current_city,
                    "district": user.current_district,
                    "state": user.current_state,
                    "pincode": user.current_pincode,
                    "country": user.current_country or "India",
                    "same_as_current": True,
                },
            )
        else:
            MemberAddress.objects.update_or_create(
                user_id=user.pk,
                address_type="permanent",
                defaults={
                    "address_line1": user.permanent_address_line1,
                    "address_line2": user.permanent_address_line2,
                    "city": user.permanent_city,
                    "district": user.permanent_district,
                    "state": user.permanent_state,
                    "pincode": user.permanent_pincode,
                    "country": user.permanent_country or "India",
                    "same_as_current": False,
                },
            )

        if user.nominee_name:
            MemberNominee.objects.create(
                user_id=user.pk,
                is_primary=True,
                name=user.nominee_name,
                relationship=user.nominee_relationship,
                dob=user.nominee_dob,
                contact=user.nominee_contact,
                address=user.nominee_address,
                id_type=user.nominee_id_type,
                id_number=user.nominee_id_number,
            )
        if user.alt_nominee_name:
            MemberNominee.objects.create(
                user_id=user.pk,
                is_primary=False,
                name=user.alt_nominee_name,
                relationship=user.alt_nominee_relationship,
                dob=user.alt_nominee_dob,
                contact=user.alt_nominee_contact,
                address=None,
                id_type=None,
                id_number=None,
            )

        shares = int(user.number_of_shares or 0)
        face = user.face_value_per_share if user.face_value_per_share is not None else Decimal("0")
        sc_amt = user.share_capital_amount if user.share_capital_amount is not None else Decimal("0")
        issue_dt = user.share_issue_date or user.date_of_joining or date.today()
        if shares > 0 or sc_amt > 0:
            total_value = (Decimal(shares) * Decimal(str(face))).quantize(Decimal("0.01"))
            if total_value == 0 and sc_amt > 0:
                total_value = Decimal(str(sc_amt)).quantize(Decimal("0.01"))
            ShareCapital.objects.create(
                user_id=user.pk,
                number_of_shares=shares,
                face_value_per_share=face,
                total_value=total_value,
                certificate_number=user.share_certificate_number,
                issue_date=issue_dt,
                redemption_date=None,
                status="issued",
            )


def phase2_reverse_copy(apps, schema_editor):
    MemberKYC = apps.get_model("accounts", "MemberKYC")
    MemberAddress = apps.get_model("accounts", "MemberAddress")
    MemberNominee = apps.get_model("accounts", "MemberNominee")
    ShareCapital = apps.get_model("accounts", "ShareCapital")
    ShareCapital.objects.all().delete()
    MemberNominee.objects.all().delete()
    MemberAddress.objects.all().delete()
    MemberKYC.objects.all().delete()


class Migration(migrations.Migration):

    dependencies = [
        ("accounts", "0028_financialperiod_instrument_transaction_and_more"),
    ]

    operations = [
        migrations.CreateModel(
            name="ShareCapital",
            fields=[
                ("id", models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name="ID")),
                ("number_of_shares", models.IntegerField(default=0)),
                ("face_value_per_share", models.DecimalField(decimal_places=2, default=0, max_digits=10)),
                ("total_value", models.DecimalField(decimal_places=2, default=0, max_digits=12)),
                ("certificate_number", models.CharField(blank=True, max_length=50, null=True)),
                ("issue_date", models.DateField()),
                ("redemption_date", models.DateField(blank=True, null=True)),
                (
                    "status",
                    models.CharField(
                        choices=[("issued", "Issued"), ("redeemed", "Redeemed"), ("transferred", "Transferred")],
                        db_index=True,
                        default="issued",
                        max_length=20,
                    ),
                ),
                ("created_at", models.DateTimeField(auto_now_add=True)),
                ("updated_at", models.DateTimeField(auto_now=True)),
                (
                    "user",
                    models.ForeignKey(
                        on_delete=django.db.models.deletion.CASCADE,
                        related_name="share_holdings",
                        to=settings.AUTH_USER_MODEL,
                    ),
                ),
            ],
            options={
                "verbose_name": "Share Capital",
                "verbose_name_plural": "Share Capital",
                "ordering": ["-issue_date", "-id"],
            },
        ),
        migrations.CreateModel(
            name="MemberNominee",
            fields=[
                ("id", models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name="ID")),
                ("is_primary", models.BooleanField(default=True)),
                ("name", models.CharField(max_length=200)),
                ("relationship", models.CharField(blank=True, max_length=100, null=True)),
                ("dob", models.DateField(blank=True, null=True)),
                ("contact", models.CharField(blank=True, max_length=15, null=True)),
                ("address", models.TextField(blank=True, null=True)),
                ("id_type", models.CharField(blank=True, max_length=50, null=True)),
                ("id_number", models.CharField(blank=True, max_length=50, null=True)),
                ("created_at", models.DateTimeField(auto_now_add=True)),
                ("updated_at", models.DateTimeField(auto_now=True)),
                (
                    "user",
                    models.ForeignKey(
                        on_delete=django.db.models.deletion.CASCADE,
                        related_name="nominees",
                        to=settings.AUTH_USER_MODEL,
                    ),
                ),
            ],
            options={
                "verbose_name": "Member Nominee",
                "verbose_name_plural": "Member Nominees",
                "ordering": ["user", "-is_primary", "id"],
            },
        ),
        migrations.CreateModel(
            name="MemberKYC",
            fields=[
                ("id", models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name="ID")),
                (
                    "kyc_status",
                    models.CharField(
                        choices=[
                            ("pending", "Pending"),
                            ("verified", "Verified"),
                            ("rejected", "Rejected"),
                            ("expired", "Expired"),
                        ],
                        default="pending",
                        max_length=20,
                    ),
                ),
                ("kyc_verified_date", models.DateField(blank=True, null=True)),
                ("kyc_verified_by", models.CharField(blank=True, max_length=200, null=True)),
                (
                    "aadhaar_number",
                    models.CharField(
                        blank=True,
                        max_length=12,
                        null=True,
                        validators=[
                            django.core.validators.RegexValidator(
                                message="Aadhaar must be 12 digits and cannot start with 0 or 1",
                                regex="^[2-9][0-9]{11}$",
                            )
                        ],
                        verbose_name="Aadhaar Number",
                    ),
                ),
                (
                    "pan_number",
                    models.CharField(
                        blank=True,
                        max_length=10,
                        null=True,
                        validators=[
                            django.core.validators.RegexValidator(
                                message="PAN must be in format: ABCDE1234F (5 letters, 4 digits, 1 letter)",
                                regex="^[A-Z]{5}[0-9]{4}[A-Z]$",
                            )
                        ],
                        verbose_name="PAN Number",
                    ),
                ),
                ("voter_id", models.CharField(blank=True, max_length=20, null=True, verbose_name="Voter ID")),
                ("passport_number", models.CharField(blank=True, max_length=20, null=True)),
                ("driving_licence", models.CharField(blank=True, max_length=20, null=True)),
                ("aadhaar_copy", models.FileField(blank=True, null=True, upload_to="kyc/aadhar/")),
                ("pan_copy", models.FileField(blank=True, null=True, upload_to="kyc/pan/")),
                ("address_proof", models.FileField(blank=True, null=True, upload_to="kyc/address/")),
                ("photograph", models.ImageField(blank=True, null=True, upload_to="kyc/photos/")),
                ("signature_specimen", models.ImageField(blank=True, null=True, upload_to="kyc/signatures/")),
                ("created_at", models.DateTimeField(auto_now_add=True)),
                ("updated_at", models.DateTimeField(auto_now=True)),
                (
                    "user",
                    models.OneToOneField(
                        on_delete=django.db.models.deletion.CASCADE, related_name="kyc", to=settings.AUTH_USER_MODEL
                    ),
                ),
            ],
            options={
                "verbose_name": "Member KYC",
                "verbose_name_plural": "Member KYC",
            },
        ),
        migrations.CreateModel(
            name="MemberAddress",
            fields=[
                ("id", models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name="ID")),
                (
                    "address_type",
                    models.CharField(
                        choices=[("current", "Current"), ("permanent", "Permanent")], db_index=True, max_length=20
                    ),
                ),
                ("address_line1", models.CharField(blank=True, max_length=255, null=True)),
                ("address_line2", models.CharField(blank=True, max_length=255, null=True)),
                ("city", models.CharField(blank=True, max_length=100, null=True)),
                ("district", models.CharField(blank=True, max_length=100, null=True)),
                ("state", models.CharField(blank=True, max_length=100, null=True)),
                (
                    "pincode",
                    models.CharField(
                        blank=True,
                        max_length=10,
                        null=True,
                        validators=[
                            django.core.validators.RegexValidator(
                                message="Pincode must be 6 digits and cannot start with 0", regex="^[1-9][0-9]{5}$"
                            )
                        ],
                    ),
                ),
                ("country", models.CharField(default="India", max_length=100)),
                ("same_as_current", models.BooleanField(default=False)),
                ("created_at", models.DateTimeField(auto_now_add=True)),
                ("updated_at", models.DateTimeField(auto_now=True)),
                (
                    "user",
                    models.ForeignKey(
                        on_delete=django.db.models.deletion.CASCADE,
                        related_name="addresses",
                        to=settings.AUTH_USER_MODEL,
                    ),
                ),
            ],
            options={
                "verbose_name": "Member Address",
                "verbose_name_plural": "Member Addresses",
                "ordering": ["user", "address_type"],
                "unique_together": {("user", "address_type")},
            },
        ),
        migrations.RunPython(phase2_copy_from_user, phase2_reverse_copy),
        migrations.RemoveField(model_name="user", name="aadhar_copy"),
        migrations.RemoveField(model_name="user", name="aadhar_number"),
        migrations.RemoveField(model_name="user", name="active_fd_accounts"),
        migrations.RemoveField(model_name="user", name="active_loan_accounts"),
        migrations.RemoveField(model_name="user", name="active_rd_accounts"),
        migrations.RemoveField(model_name="user", name="active_savings_accounts"),
        migrations.RemoveField(model_name="user", name="address_proof"),
        migrations.RemoveField(model_name="user", name="alt_nominee_contact"),
        migrations.RemoveField(model_name="user", name="alt_nominee_dob"),
        migrations.RemoveField(model_name="user", name="alt_nominee_name"),
        migrations.RemoveField(model_name="user", name="alt_nominee_relationship"),
        migrations.RemoveField(model_name="user", name="current_address_line1"),
        migrations.RemoveField(model_name="user", name="current_address_line2"),
        migrations.RemoveField(model_name="user", name="current_city"),
        migrations.RemoveField(model_name="user", name="current_country"),
        migrations.RemoveField(model_name="user", name="current_district"),
        migrations.RemoveField(model_name="user", name="current_pincode"),
        migrations.RemoveField(model_name="user", name="current_state"),
        migrations.RemoveField(model_name="user", name="driving_license"),
        migrations.RemoveField(model_name="user", name="face_value_per_share"),
        migrations.RemoveField(model_name="user", name="kyc_status"),
        migrations.RemoveField(model_name="user", name="kyc_verified_by"),
        migrations.RemoveField(model_name="user", name="kyc_verified_date"),
        migrations.RemoveField(model_name="user", name="nominee_address"),
        migrations.RemoveField(model_name="user", name="nominee_contact"),
        migrations.RemoveField(model_name="user", name="nominee_dob"),
        migrations.RemoveField(model_name="user", name="nominee_id_number"),
        migrations.RemoveField(model_name="user", name="nominee_id_type"),
        migrations.RemoveField(model_name="user", name="nominee_name"),
        migrations.RemoveField(model_name="user", name="nominee_relationship"),
        migrations.RemoveField(model_name="user", name="number_of_shares"),
        migrations.RemoveField(model_name="user", name="pan_copy"),
        migrations.RemoveField(model_name="user", name="pan_number"),
        migrations.RemoveField(model_name="user", name="passport_number"),
        migrations.RemoveField(model_name="user", name="permanent_address_line1"),
        migrations.RemoveField(model_name="user", name="permanent_address_line2"),
        migrations.RemoveField(model_name="user", name="permanent_city"),
        migrations.RemoveField(model_name="user", name="permanent_country"),
        migrations.RemoveField(model_name="user", name="permanent_district"),
        migrations.RemoveField(model_name="user", name="permanent_pincode"),
        migrations.RemoveField(model_name="user", name="permanent_same_as_current"),
        migrations.RemoveField(model_name="user", name="permanent_state"),
        migrations.RemoveField(model_name="user", name="photograph"),
        migrations.RemoveField(model_name="user", name="share_capital_amount"),
        migrations.RemoveField(model_name="user", name="share_certificate_number"),
        migrations.RemoveField(model_name="user", name="share_issue_date"),
        migrations.RemoveField(model_name="user", name="signature_specimen"),
        migrations.RemoveField(model_name="user", name="total_accounts_count"),
        migrations.RemoveField(model_name="user", name="total_deposit_balance"),
        migrations.RemoveField(model_name="user", name="total_loan_outstanding"),
        migrations.RemoveField(model_name="user", name="voter_id"),
    ]
