# Generated by Django 4.2.30 on 2026-04-12 16:32

from django.conf import settings
import django.core.validators
from django.db import migrations, models
import django.db.models.deletion


def _set_existing_interest_payouts_credited(apps, schema_editor):
    InterestPayout = apps.get_model("accounts", "InterestPayout")
    InterestPayout.objects.all().update(status="credited")


class Migration(migrations.Migration):

    dependencies = [
        ('accounts', '0030_loan_phase3_split'),
    ]

    operations = [
        migrations.CreateModel(
            name='FeeSchedule',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('fee_type', models.CharField(choices=[('membership', 'Membership'), ('processing', 'Processing'), ('late_payment', 'Late Payment'), ('annual_maintenance', 'Annual Maintenance'), ('closure', 'Closure'), ('npa', 'NPA')], db_index=True, max_length=30)),
                ('name', models.CharField(max_length=200)),
                ('amount', models.DecimalField(blank=True, decimal_places=2, max_digits=10, null=True)),
                ('percentage', models.DecimalField(blank=True, decimal_places=2, max_digits=5, null=True, verbose_name='Percentage of base')),
                ('applies_to', models.CharField(choices=[('loan', 'Loan'), ('account', 'Account'), ('membership', 'Membership')], db_index=True, max_length=20)),
                ('is_active', models.BooleanField(db_index=True, default=True)),
                ('effective_date', models.DateField()),
                ('description', models.TextField(blank=True, null=True)),
                ('created_at', models.DateTimeField(auto_now_add=True)),
            ],
            options={
                'verbose_name': 'Fee Schedule',
                'verbose_name_plural': 'Fee Schedules',
                'ordering': ['-effective_date', 'fee_type'],
            },
        ),
        migrations.AlterModelOptions(
            name='fundallocationrule',
            options={'ordering': ['priority_order', 'trigger_event', 'fund'], 'verbose_name': 'Fund Allocation Rule', 'verbose_name_plural': 'Fund Allocation Rules'},
        ),
        migrations.AddField(
            model_name='fundallocationrule',
            name='max_cap',
            field=models.DecimalField(blank=True, decimal_places=2, help_text='Cap this rule’s allocation at this amount (after percentage/fixed calc).', max_digits=15, null=True, verbose_name='Maximum allocation'),
        ),
        migrations.AddField(
            model_name='fundallocationrule',
            name='min_threshold',
            field=models.DecimalField(blank=True, decimal_places=2, help_text='Skip allocation if trigger total is below this amount.', max_digits=10, null=True, verbose_name='Minimum source amount'),
        ),
        migrations.AddField(
            model_name='fundallocationrule',
            name='priority_order',
            field=models.IntegerField(default=0, help_text='Lower runs first when multiple rules match the same trigger.', verbose_name='Priority'),
        ),
        migrations.AddField(
            model_name='fundtransaction',
            name='allocation_rule',
            field=models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.SET_NULL, related_name='fund_transactions', to='accounts.fundallocationrule'),
        ),
        migrations.AddField(
            model_name='fundtransaction',
            name='financial_period',
            field=models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.SET_NULL, related_name='fund_transactions', to='accounts.financialperiod'),
        ),
        migrations.AddField(
            model_name='interestpayout',
            name='financial_period',
            field=models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.SET_NULL, related_name='interest_payouts', to='accounts.financialperiod'),
        ),
        migrations.AddField(
            model_name='interestpayout',
            name='status',
            field=models.CharField(choices=[('accrued', 'Accrued'), ('credited', 'Credited')], db_index=True, default='accrued', max_length=20),
        ),
        migrations.AddField(
            model_name='interestpayout',
            name='transaction',
            field=models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.SET_NULL, related_name='interest_payouts', to='accounts.transaction'),
        ),
        migrations.RunPython(_set_existing_interest_payouts_credited, migrations.RunPython.noop),
        migrations.AlterField(
            model_name='guarantor',
            name='contact',
            field=models.CharField(blank=True, max_length=15, null=True, validators=[django.core.validators.RegexValidator(message='Phone must be 10 digits starting with 6, 7, 8, or 9', regex='^[6-9][0-9]{9}$')]),
        ),
        migrations.CreateModel(
            name='SocietyAccount',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('total_member_deposits', models.DecimalField(decimal_places=2, default=0, max_digits=15)),
                ('total_loan_outstanding', models.DecimalField(decimal_places=2, default=0, max_digits=15)),
                ('total_interest_payable', models.DecimalField(decimal_places=2, default=0, max_digits=15)),
                ('total_interest_receivable', models.DecimalField(decimal_places=2, default=0, max_digits=15)),
                ('total_fees_collected', models.DecimalField(decimal_places=2, default=0, max_digits=15)),
                ('total_fund_balance', models.DecimalField(decimal_places=2, default=0, max_digits=15)),
                ('net_surplus', models.DecimalField(decimal_places=2, default=0, max_digits=15)),
                ('last_updated', models.DateTimeField(auto_now=True)),
                ('created_at', models.DateTimeField(auto_now_add=True)),
                ('financial_period', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='society_accounts', to='accounts.financialperiod')),
            ],
            options={
                'verbose_name': 'Society Account Snapshot',
                'verbose_name_plural': 'Society Account Snapshots',
                'ordering': ['-last_updated'],
            },
        ),
        migrations.CreateModel(
            name='ProfitAndLoss',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('loan_interest_income', models.DecimalField(decimal_places=2, default=0, max_digits=15)),
                ('processing_fees_income', models.DecimalField(decimal_places=2, default=0, max_digits=15)),
                ('penalty_income', models.DecimalField(decimal_places=2, default=0, max_digits=15)),
                ('membership_fees_income', models.DecimalField(decimal_places=2, default=0, max_digits=15)),
                ('other_income', models.DecimalField(decimal_places=2, default=0, max_digits=15)),
                ('total_income', models.DecimalField(decimal_places=2, default=0, max_digits=15)),
                ('deposit_interest_expense', models.DecimalField(decimal_places=2, default=0, max_digits=15)),
                ('bad_debt_expense', models.DecimalField(decimal_places=2, default=0, max_digits=15)),
                ('other_expense', models.DecimalField(decimal_places=2, default=0, max_digits=15)),
                ('total_expense', models.DecimalField(decimal_places=2, default=0, max_digits=15)),
                ('gross_surplus', models.DecimalField(decimal_places=2, default=0, max_digits=15)),
                ('fund_allocations_total', models.DecimalField(decimal_places=2, default=0, max_digits=15)),
                ('net_surplus', models.DecimalField(decimal_places=2, default=0, max_digits=15)),
                ('calculation_date', models.DateTimeField()),
                ('is_locked', models.BooleanField(default=False)),
                ('locked_date', models.DateTimeField(blank=True, null=True)),
                ('created_at', models.DateTimeField(auto_now_add=True)),
                ('updated_at', models.DateTimeField(auto_now=True)),
                ('calculated_by', models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.SET_NULL, related_name='profit_loss_calculations', to=settings.AUTH_USER_MODEL)),
                ('financial_period', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='profit_and_loss_snapshots', to='accounts.financialperiod')),
                ('locked_by', models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.SET_NULL, related_name='profit_loss_locked', to=settings.AUTH_USER_MODEL)),
            ],
            options={
                'verbose_name': 'Profit and Loss',
                'verbose_name_plural': 'Profit and Loss',
                'ordering': ['-calculation_date'],
            },
        ),
        migrations.CreateModel(
            name='InterestReceivable',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('amount_accrued', models.DecimalField(decimal_places=2, max_digits=12)),
                ('amount_collected', models.DecimalField(decimal_places=2, default=0, max_digits=12)),
                ('status', models.CharField(choices=[('accrued', 'Accrued'), ('collected', 'Collected'), ('written_off', 'Written Off')], db_index=True, default='accrued', max_length=20)),
                ('due_date', models.DateField()),
                ('collected_date', models.DateField(blank=True, null=True)),
                ('created_at', models.DateTimeField(auto_now_add=True)),
                ('financial_period', models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.SET_NULL, related_name='interest_receivables', to='accounts.financialperiod')),
                ('loan_account', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='interest_receivables', to='accounts.loanaccount')),
            ],
            options={
                'verbose_name': 'Interest Receivable',
                'verbose_name_plural': 'Interest Receivables',
                'ordering': ['-created_at'],
            },
        ),
        migrations.CreateModel(
            name='FeeCharge',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('amount', models.DecimalField(decimal_places=2, max_digits=10)),
                ('status', models.CharField(choices=[('charged', 'Charged'), ('waived', 'Waived'), ('refunded', 'Refunded')], db_index=True, default='charged', max_length=20)),
                ('waived_reason', models.TextField(blank=True, null=True)),
                ('created_at', models.DateTimeField(auto_now_add=True)),
                ('fee_schedule', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='charges', to='accounts.feeschedule')),
                ('loan_account', models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.CASCADE, related_name='fee_charges', to='accounts.loanaccount')),
                ('member_account', models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.CASCADE, related_name='fee_charges', to='accounts.memberaccount')),
                ('transaction', models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.SET_NULL, related_name='fee_charges', to='accounts.transaction')),
                ('user', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='fee_charges', to=settings.AUTH_USER_MODEL)),
                ('waived_by', models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.SET_NULL, related_name='fee_charges_waived', to=settings.AUTH_USER_MODEL)),
            ],
            options={
                'verbose_name': 'Fee Charge',
                'verbose_name_plural': 'Fee Charges',
                'ordering': ['-created_at'],
            },
        ),
    ]
