# Generated by Django 4.2.30 on 2026-04-12 16:44

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('accounts', '0031_phase4_financial_tracking'),
    ]

    operations = [
        migrations.AlterUniqueTogether(
            name='interestreceivable',
            unique_together={('loan_account', 'due_date')},
        ),
    ]
