# Generated by Django 4.2.30 on 2026-04-12 17:17

from django.db import migrations, models


def _merge_duplicate_snapshots(apps, schema_editor):
    ProfitAndLoss = apps.get_model("accounts", "ProfitAndLoss")
    SocietyAccount = apps.get_model("accounts", "SocietyAccount")

    for fp_id in ProfitAndLoss.objects.values_list("financial_period_id", flat=True).distinct():
        rows = list(
            ProfitAndLoss.objects.filter(financial_period_id=fp_id).order_by("-calculation_date", "-id")
        )
        for row in rows[1:]:
            row.delete()

    for fp_id in SocietyAccount.objects.values_list("financial_period_id", flat=True).distinct():
        rows = list(SocietyAccount.objects.filter(financial_period_id=fp_id).order_by("-last_updated", "-id"))
        for row in rows[1:]:
            row.delete()


class Migration(migrations.Migration):

    dependencies = [
        ('accounts', '0032_interestreceivable_unique_together'),
    ]

    operations = [
        migrations.RunPython(_merge_duplicate_snapshots, migrations.RunPython.noop),
        migrations.AddConstraint(
            model_name='profitandloss',
            constraint=models.UniqueConstraint(fields=('financial_period',), name='uniq_profitandloss_financial_period'),
        ),
        migrations.AddConstraint(
            model_name='societyaccount',
            constraint=models.UniqueConstraint(fields=('financial_period',), name='uniq_societyaccount_financial_period'),
        ),
    ]
