# Generated by Django 4.2.30 on 2026-04-13 11:00

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ("accounts", "0033_profit_loss_society_unique_period"),
    ]

    operations = [
        migrations.CreateModel(
            name="SocietyConfiguration",
            fields=[
                ("id", models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name="ID")),
                ("society_name", models.CharField(max_length=255)),
                ("society_logo", models.ImageField(blank=True, null=True, upload_to="society/logo/")),
                ("late_payment_penalty_per_day", models.DecimalField(decimal_places=2, default=0, max_digits=8)),
                ("setup_completed_at", models.DateTimeField(blank=True, null=True)),
                ("created_at", models.DateTimeField(auto_now_add=True)),
                ("updated_at", models.DateTimeField(auto_now=True)),
            ],
            options={
                "verbose_name": "Society Configuration",
                "verbose_name_plural": "Society Configuration",
                "ordering": ["id"],
            },
        ),
        migrations.CreateModel(
            name="LoanTypeConfiguration",
            fields=[
                ("id", models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name="ID")),
                (
                    "loan_type",
                    models.CharField(
                        choices=[
                            ("personal", "Personal Loan"),
                            ("home", "Home Loan"),
                            ("vehicle", "Vehicle Loan"),
                            ("gold", "Gold Loan"),
                            ("education", "Education Loan"),
                            ("business", "Business Loan"),
                            ("emergency", "Emergency Loan"),
                            ("agriculture", "Agriculture Loan"),
                        ],
                        max_length=20,
                        unique=True,
                    ),
                ),
                ("interest_rate", models.DecimalField(decimal_places=2, max_digits=5)),
                ("is_active", models.BooleanField(default=True)),
                ("display_order", models.IntegerField(default=0)),
                ("created_at", models.DateTimeField(auto_now_add=True)),
                ("updated_at", models.DateTimeField(auto_now=True)),
            ],
            options={
                "verbose_name": "Loan Type Configuration",
                "verbose_name_plural": "Loan Type Configurations",
                "ordering": ["display_order", "loan_type"],
            },
        ),
        migrations.CreateModel(
            name="AccountTypeConfiguration",
            fields=[
                ("id", models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name="ID")),
                (
                    "account_type",
                    models.CharField(
                        choices=[
                            ("fd", "Fixed Deposit"),
                            ("cd", "Certificate of Deposit"),
                            ("rd", "Recurring Deposit"),
                            ("od", "Overdraft"),
                            ("share", "Share Account"),
                            ("sukanya", "Sukanya Yojana"),
                            ("suputra", "Suputra Yojana"),
                        ],
                        max_length=20,
                        unique=True,
                    ),
                ),
                ("interest_rate", models.DecimalField(decimal_places=2, max_digits=5)),
                ("is_active", models.BooleanField(default=True)),
                ("display_order", models.IntegerField(default=0)),
                ("created_at", models.DateTimeField(auto_now_add=True)),
                ("updated_at", models.DateTimeField(auto_now=True)),
            ],
            options={
                "verbose_name": "Account Type Configuration",
                "verbose_name_plural": "Account Type Configurations",
                "ordering": ["display_order", "account_type"],
            },
        ),
    ]
