# Generated by Django 4.2.30 on 2026-04-13 15:10

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ("accounts", "0034_societyconfiguration_and_product_configs"),
    ]

    operations = [
        migrations.AlterField(
            model_name="accounttypeconfiguration",
            name="account_type",
            field=models.CharField(max_length=100, unique=True),
        ),
        migrations.AlterField(
            model_name="loantypeconfiguration",
            name="loan_type",
            field=models.CharField(max_length=100, unique=True),
        ),
    ]
